# Vader Exploration

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import nltk
import glob
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from nltk.stem import WordNetLemmatizer
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
import re

pd.set_option('display.max_colwidth', 50)
pd.set_option('display.max_rows', 10000)

# %matplotlib inline
# from google.colab import drive
# drive.mount('/content/drive')

In [1]:
from os import listdir
from os.path import isfile, join

# get filenames of everything successfully scraped
mypath = './tagged_comments/'
tagged_comments = [f for f in listdir(mypath) if isfile(join(mypath, f))]


FileNotFoundError: [WinError 3] The system cannot find the path specified: './tagged_comments/'

In [6]:
# !cp "/content/drive/MyDrive/Colab Notebooks/comments_and_tags.csv" "comments_and_tags.csv"

df_vader = pd.read_csv('comments_and_tags.csv', index_col= 'Unnamed: 0', encoding='utf-8')
df_vader = df_vader[['sentiment','body']]
df_vader

sentiment                                               body
0             0  Thanks but you’ve lost me at \n\n„If look at A...
1             1  Awesome 😎! Why the moon 🤔 Let’s shoot AMC out ...
2             1  If you look at AMCs business page you’ll find ...
3             1  I bought 20 today, i am also a retarded dumb m...
4             0  Ahh, my fellow Retard. I see the more and more...
5             0  Thanks, heard y’all were pretty good at trench...
6             0  I fingered this girl I met off instagram durin...
7             0  I can say I have done this fortunately or unfo...
8             0  Try watching the move a quiet place in a dine ...
9             0  This. If movie theaters didn't exist, young pe...
10            0                  He probably gets off on watching.
11            0  You lyin, 7.50/hr ain't even close to enough t...
12            0  Most of the movie theaters here in Wisconsin (...
13            0  AMC personally sent an employee to my house to...
14            0  Yes, this is a classic example of a place to p...
15            0  Dude you’re supposed to say you saw something ...
16            0  I go for the passive aggressive popcorn flick....
17            0  went to see some movie with my fuck buddy year...
18            0  I once bit into one of their hot dogs and ther...
19            0  1,000 feet in Florida my man, enjoy that crisp...
20            0  Had a Tinder hookup in the back of her Jeep in...
21            0  I'm in ATL and my group saw Black Widow this p...
22            1  That seems like it's your local theater that's...
23            0  I can finger someone in a cinema full of kids ...
24            1  Movies or movie theatres will be here to stay?...
25            0            Popcorn needs to be served by strippers
26            0  Weird, I’ve been to two movies in two weeks (i...
27            0  Just gotta out-psychopath them.  I had four du...
28            0      gettin a BJ in the theater will never get old
29            0  I will never go to a movie theater again, I wa...
30            0  It might've not killed the radio star but radi...
31            0  I got an awkward handy in a packed theater whe...
32            0  &gt;numbers don’t lie and more people went to ...
33            0        I read way too many of these comments….🤦‍♂️
34            0         You’ve never been to a black movie theater
35            1  The squeeze happened. It went from ~6 to 70. T...
36            0  Bad local management, the AMC by me is much be...
37            0  Doubt it. They aren't the ones losing money it...
38            0  😂😂😂😂😂😂 this is the comment of the thread I’m g...
39            0  yes but sporting events you get to watch the g...
40            0  So you are celebrating giving them money when ...
41            0  &gt; $9 beer and the annoying crowd\n\nSo like...
42            0  Sporting events are events; they are parties. ...
43            0  what? the actors don't show up at the theater ...
44            0  not really, you should be comparing going to t...
45            0  If movie theatres are going to survive, they h...
46            0       That’s what I think of to conjure a patronus
47            0      and now you can only beat off to wizard porn?
48            0  yeah except I can't have a bunch of profession...
49            0  I got my first HJ in the back of an AMC watchi...
50            0  Movie theaters will become a niche thing in a ...
51            0  This is Why I like my county where we sit in s...
52            0  AMC poisoned our water supply, burned our crop...
53            1  Yeah they're going to need to do like launch e...
54            1  AMC was in trouble and a less than satisfactor...
55            1  but you're as retarded as old wsb which is 100...
56            0  Hey baby! Go home! It’s 3 o’clock in the morni...
57            1  It’s literally the same argument. “It’s too ex...
58           -1  Mainly boomers and 16 year olds who 

https://storage.googleapis.com/kagglesdsdata/datasets/2037/3472/vader_lexicon/vader_lexicon.txt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20220227%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20220227T100024Z&X-Goog-Expires=259199&X-Goog-SignedHeaders=host&X-Goog-Signature=530569f3b40eaaf8b4d2a76745b8da3098d593403fcf0be0c021c732a15c1c19c29a6a415907abb3804c12f3f8b8993d6ba002ca49f321c2db1a33f779824cff106627b7e840a0ca86c69629d09ca24f2c1f3ffd2aed8cac851893e4389012f91e22d817d21ce518b7a599619e3ee265257e2b324129c1d9a3fcb71a69b68723e5da8cccc21a05b1e4adbecdbcdb24bdcd46f3404829739c79f756f6512dd27237f87d00dd44b8c184009e70653a9fdb3da89bd2c5f7aa3e359f94bc921d5bb6a41edeb6bd8bdd495bf91246241e284c8383f73621d7b9bc515ae55c03a19253d049cfaa001c01129bd917a51533916229c337164696a22bc7097d02e81b156c

Original vader lexicon dictionary

https://medium.com/@piocalderon/vader-sentiment-analysis-explained-f1c4f9101cd9 - nice write up on how vader works

# EDA

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import nltk
import glob
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from nltk.stem import WordNetLemmatizer
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
import re
# !pip install demoji
import demoji

pd.set_option('display.max_colwidth', 50)

%matplotlib inline

In [ ]:
def find_pos(word):
    # Part of Speech constants
    # ADJ, ADJ_SAT, ADV, NOUN, VERB = 'a', 's', 'r', 'n', 'v'
    pos= nltk.pos_tag(nltk.word_tokenize(word))[0][1]
    # Adjective tags -'JJ', 'JJR', 'JJS'
    if pos.lower()[0] == 'j':
        return 'a'
    # Adverb tags -'RB', 'RBR', 'RBS'
    elif pos.lower()[0] == 'r':
        return 'r'
    # Verb tags -'VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ'
    elif pos.lower()[0] == 'v':
        return 'v'
    # Noun tags -'NN', 'NNS', 'NNP', 'NNPS'
    else:
        return 'n'

demoji.download_codes()

def remove_emoji(text):
    dem = demoji.findall(text)
    for item in dem.keys():
        text = text.replace(item,'')
        
    return text

# Function to apply lemmatization to a list of words
def words_lemmatizer(text, encoding="utf8"):
    words = nltk.word_tokenize(text)
    lemma_words = []
    wl= WordNetLemmatizer()
    for word in words:
        pos= find_pos(word)
        lemma_words.append(wl.lemmatize(word, pos))
    return " ".join(lemma_words)

def remove_stopwords(text, lang='english'):
    new_words = ['take','let','come','look','still','say','week','next','right','day',\
                 'time','let','back','look','lol','think','thing','clov','amc','nok','bb','gme'] #insert all additional stopwords you want to remove here
    custom = nltk.corpus.stopwords.words('english')
    custom.extend(new_words)
    words = nltk.word_tokenize(text)
    lang_stopwords = stopwords.words(lang)
    stopwords_removed = [w for w in words if w.lower() not in lang_stopwords]
    removing_custom_words = [words for words in stopwords_removed if not words in custom]
    return " ".join(removing_custom_words)

def do_prepocessing(one_row):
    lower_text = one_row.lower()
    
    remove_emoji_text = remove_emoji(lower_text) # Remove emojis

    remove_unwanted_charectors = re.sub(r'[^a-zA-Z0-9_#@&\s]', ' ', remove_emoji_text) # Remove unwanted charectors like punctuations andnon ascii 
    remove_unwanted_charectors = re.sub(r'&[\w]+', ' ', remove_unwanted_charectors) # Remove &amp, *&words etc
    
    removed_extra_space = re.sub(r'\s+',' ', remove_unwanted_charectors) # Remove extra white_spaces
    
    extract_hash = re.findall(r'#[\w]+', removed_extra_space) # Extract #hashTags
    extract_has_joined = " ".join(extract_hash)
    removed_hash_text = re.sub(r'#[\w]+', '', removed_extra_space) # Remove #hastags
    
    remove_atrate = re.findall(r'@[\w]+', removed_hash_text) # Extract @Users
    removed_atrate = re.sub(r'@[\w]+', '', removed_hash_text) # Remove @Users
    
    removed_stopwords_text = remove_stopwords(removed_atrate)
    lemmatize_text = words_lemmatizer(removed_stopwords_text)
    return lemmatize_text

C:\ProgramData\Anaconda3\envs\5153env\lib\site-packages\ipykernel_launcher.py:18: FutureWarning: The demoji.download_codes attribute is deprecated and will be removed from demoji in a future version. It is an unused attribute as emoji codes are now distributed directly with the demoji package.


In [ ]:
new_words = ['take','let','come','look','still','say','week','next','right','day','pltr','wish',\
                 'time','let','back','look','lol','think','thing','clov','amc','nok','bb','gme','br','href','clne','shares','stock'] 
stopwords = set(STOPWORDS)
stopwords.update(new_words) 

In [ ]:
# negative = df_vader[df_vader['sentiment']==-1]
## good and great removed because they were included in negative sentiment
# neg = " ".join(review for review in negative.body)
# wordcloud2 = WordCloud(stopwords=stopwords).generate(neg)
# plt.imshow(wordcloud2, interpolation='bilinear')
# plt.axis("off")
# plt.savefig('wordcloudneg.png')
# plt.show()



negative['body'] = negative['body'].astype(str)
negative['body'] = negative['body'].apply(do_prepocessing)

# Create dictionary
processed = negative['body']

# Create a complete corpus from all text
textt = " ".join(text for text in processed)

# Split corpus into list of words
words = nltk.word_tokenize(textt)

# Create dictionary
from collections import Counter
my_counter = Counter(words)

# Send to df and export to csv
counts_df = pd.DataFrame.from_dict(my_counter, orient='index').reset_index()
counts_df.to_csv('dictionary_negative.csv')

C:\ProgramData\Anaconda3\envs\5153env\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
C:\ProgramData\Anaconda3\envs\5153env\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]


In [ ]:
# neutral = df_vader[df_vader['sentiment']==0]

# ## good and great removed because they were included in negative sentiment
# neut = " ".join(review for review in neutral.body)
# wordcloud2 = WordCloud(stopwords=stopwords).generate(neut)
# plt.imshow(wordcloud2, interpolation='bilinear')
# plt.axis("off")
# plt.savefig('wordcloudneut.png')
# plt.show()



neutral['body'] = neutral['body'].astype(str)
neutral['body'] = neutral['body'].apply(do_prepocessing)

# Create dictionary
processed = neutral['body']

# Create a complete corpus from all text
textt = " ".join(text for text in processed)

# Split corpus into list of words
words = nltk.word_tokenize(textt)

# Create dictionary
from collections import Counter
my_counter = Counter(words)

# Send to df and export to csv
counts_df = pd.DataFrame.from_dict(my_counter, orient='index').reset_index()
counts_df.to_csv('dictionary_neutral.csv')

C:\ProgramData\Anaconda3\envs\5153env\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\ProgramData\Anaconda3\envs\5153env\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
# positive = df_vader[df_vader['sentiment']==1]
# ## good and great removed because they were included in negative sentiment
# pos = " ".join(review for review in positive.body)
# wordcloud2 = WordCloud(stopwords=stopwords).generate(pos)
# plt.imshow(wordcloud2, interpolation='bilinear')
# plt.axis("off")
# plt.savefig('wordcloudpos.png')
# plt.show()


positive['body'] = positive['body'].astype(str)
positive['body'] = positive['body'].apply(do_prepocessing)

# Create dictionary
processed = positive['body']

# Create a complete corpus from all text
textt = " ".join(text for text in processed)

# Split corpus into list of words
words = nltk.word_tokenize(textt)

# Create dictionary
from collections import Counter
my_counter = Counter(words)

# Send to df and export to csv
counts_df = pd.DataFrame.from_dict(my_counter, orient='index').reset_index()
counts_df.to_csv('dictionary_positive.csv')

C:\ProgramData\Anaconda3\envs\5153env\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\ProgramData\Anaconda3\envs\5153env\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':


## Cleaning functions

In [ ]:
nltk.download('averaged_perceptron_tagger')

def find_pos(word):
    # Part of Speech constants
    # ADJ, ADJ_SAT, ADV, NOUN, VERB = 'a', 's', 'r', 'n', 'v'
    pos= nltk.pos_tag(nltk.word_tokenize(word))[0][1]
    # Adjective tags -'JJ', 'JJR', 'JJS'
    if pos.lower()[0] == 'j':
        return 'a'
    # Adverb tags -'RB', 'RBR', 'RBS'
    elif pos.lower()[0] == 'r':
        return 'r'
    # Verb tags -'VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ'
    elif pos.lower()[0] == 'v':
        return 'v'
    # Noun tags -'NN', 'NNS', 'NNP', 'NNPS'
    else:
        return 'n'

# demoji.download_codes()

def remove_emoji(text):
#     dem = demoji.findall(text)
#     for item in dem.keys():
#         text = text.replace(item,'')

    import emoji
    text = emoji.demojize(text, delimiters=(" ", " "))
    return text

# Function to apply lemmatization to a list of words
def words_lemmatizer(text, encoding="utf8"):
    words = nltk.word_tokenize(text)
    lemma_words = []
    wl= WordNetLemmatizer()
    for word in words:
        pos= find_pos(word)
        lemma_words.append(wl.lemmatize(word, pos))
    return " ".join(lemma_words)

def remove_stopwords(text, lang='english'):
    new_words = ['take','let','come','look','still','say','week','next',\
                 'right','day','time','let','back','look','lol','think','thing'] #insert all additional stopwords you want to remove here
    custom = nltk.corpus.stopwords.words('english')
    custom.extend(new_words)
    words = nltk.word_tokenize(text)
    lang_stopwords = stopwords.words(lang)
    stopwords_removed = [w for w in words if w.lower() not in lang_stopwords]
    removing_custom_words = [words for words in stopwords_removed if not words in custom]
    return " ".join(removing_custom_words)

def do_prepocessing(one_row):
    lower_text = one_row.lower()
    
    remove_emoji_text = lower_text # line to pass through emoji as vader can handle utf8 encoded emojis
    remove_emoji_text = remove_emoji(lower_text) # Remove emojis
    
    remove_links = re.sub(r'http\S+','', lower_text) #remove links
    remove_unwanted_charectors = re.sub(r'[^a-zA-Z0-9_#@&\s]', ' ', remove_links) # Remove unwanted charectors like punctuations andnon ascii 
    remove_unwanted_charectors = re.sub(r'&[\w]+', ' ', remove_unwanted_charectors) # Remove &amp, *&words etc
    
    removed_extra_space = re.sub(r'\s+',' ', remove_unwanted_charectors) # Remove extra white_spaces
    
    extract_hash = re.findall(r'#[\w]+', removed_extra_space) # Extract #hashTags
    extract_has_joined = " ".join(extract_hash)
    removed_hash_text = re.sub(r'#[\w]+', '', removed_extra_space) # Remove #hastags
    
    remove_atrate = re.findall(r'@[\w]+', removed_hash_text) # Extract @Users
    removed_atrate = re.sub(r'@[\w]+', '', removed_hash_text) # Remove @Users
    
    removed_stopwords_text = remove_stopwords(removed_atrate)
    lemmatize_text = words_lemmatizer(removed_stopwords_text)
    return lemmatize_text



[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\chuaz\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


# Vader


In [4]:
nltk.download('vader_lexicon')
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer



[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\chuaz\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


In [12]:
def metrics(x):
    from sklearn.metrics import confusion_matrix
    from sklearn.metrics import f1_score
    from sklearn.metrics import precision_score
    from sklearn.metrics import recall_score
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import balanced_accuracy_score
    print(confusion_matrix(x['sentiment'], x['vader_sentiment'], labels= [-1,0,1]))
    print('F1 score no weighting')
    print(f1_score(x['sentiment'], x['vader_sentiment'],average=None))
    print('F1 score weighted')
    print(f1_score(x['sentiment'], x['vader_sentiment'], average='weighted'))
    print('Precision Score')
    print(precision_score(x['sentiment'], x['vader_sentiment'], average = 'weighted'))
    print('Balanced Accuracy')
    print(balanced_accuracy_score(x['sentiment'], x['vader_sentiment']))

## Trial without cleaning

In [22]:
def sentiment_score(x):
    SIA = SentimentIntensityAnalyzer()
    scores = list(SIA.polarity_scores(x).values())
    return scores[0], scores[1], scores[2], scores[3]

def sentiment(x):
    if x >0: # can be adjusted
        return 1
    elif x ==0:
        return 0
    else:
        return -1
    
def sentiment_binary(x):
    if x >0.05: # can be adjusted
        return 1
    else:
        return 0
    
def metrics_binary(x):
    from sklearn.metrics import confusion_matrix
    from sklearn.metrics import f1_score
    from sklearn.metrics import precision_score
    from sklearn.metrics import recall_score
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import balanced_accuracy_score
    print(confusion_matrix(x['sentiment_binary'], x['vader_sentiment_binary'], labels= [0,1]))
    print('F1 score no weighting')
    print(f1_score(x['sentiment_binary'], x['vader_sentiment_binary'],average=None))
    print('Precision Score')
    print(precision_score(x['sentiment_binary'], x['vader_sentiment_binary']))
    print('Balanced Accuracy')
    print(balanced_accuracy_score(x['sentiment_binary'], x['vader_sentiment_binary']))

In [10]:
%%time
df_vader["neg_score"], df_vader["neut_score"], df_vader["pos_score"], df_vader["final_score"]= zip(*df_vader['body'].apply(sentiment_score))
df_vader['vader_sentiment'] = df_vader["final_score"].apply(sentiment)

df_vader.head()

Wall time: 1min 12s


sentiment                                               body  neg_score  \
0          0  Thanks but you’ve lost me at \n\n„If look at A...      0.135   
1          1  Awesome 😎! Why the moon 🤔 Let’s shoot AMC out ...      0.073   
2          1  If you look at AMCs business page you’ll find ...      0.102   
3          1  I bought 20 today, i am also a retarded dumb m...      0.276   
4          0  Ahh, my fellow Retard. I see the more and more...      0.234   

   neut_score  pos_score  final_score  vader_sentiment  
0       0.776      0.089      -0.2500               -1  
1       0.701      0.225       0.7177                1  
2       0.686      0.212       0.6792                1  
3       0.630      0.094      -0.6808               -1  
4       0.766      0.000      -0.7469               -1

In [ ]:
# Confusion matrix whose i-th row and j-th column entry indicates the number of samples
# with true label being i-th class and predicted label being j-th class.
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
print(confusion_matrix(df_vader['sentiment'], df_vader['vader_sentiment'], labels= [-1,0,1]))
print('F1 score no weighting')
print(f1_score(df_vader['sentiment'], df_vader['vader_sentiment'],average=None))
print('F1 score weighted')
print(f1_score(df_vader['sentiment'], df_vader['vader_sentiment'], average='weighted'))
df_vader.head()

[[ 167   63  137]
 [ 692  711 1118]
 [ 495  817 1288]]
F1 score no weighting
[0.19407321 0.34581712 0.50087498]
F1 score weighted
0.4091298773977518


sentiment                                               body  neg_score  \
0          0  Thanks but you’ve lost me at \n\n„If look at A...      0.135   
1          1  Awesome 😎! Why the moon 🤔 Let’s shoot AMC out ...      0.073   
2          1  If you look at AMCs business page you’ll find ...      0.102   
3          1  I bought 20 today, i am also a retarded dumb m...      0.276   
4          1  Ahh, my fellow Retard. I see the more and more...      0.234   

   neut_score  pos_score  final_score  vader_sentiment  
0       0.776      0.089      -0.2500               -1  
1       0.701      0.225       0.7177                1  
2       0.686      0.212       0.6792                1  
3       0.630      0.094      -0.6808               -1  
4       0.766      0.000      -0.7469               -1

In [13]:
metrics(df_vader)

[[ 150   62  129]
 [ 718  757 1183]
 [ 486  773 1231]]
F1 score no weighting
[0.17699115 0.35623529 0.48917147]
F1 score weighted
0.40540432686380007
Precision Score
0.4567328688921618
Balanced Accuracy
0.4063536033145776


In [16]:
df_vader['sentiment_binary'] = df_vader['sentiment'].apply(lambda x: 1 if x ==1 else 0)
df_vader['vader_sentiment_binary'] = df_vader["final_score"].apply(sentiment_binary)
metrics_binary(df_vader)

[[1706 1293]
 [1268 1222]]
F1 score no weighting
[0.57123723 0.48831169]
Precision Score
0.48588469184890654
Balanced Accuracy
0.5298096688186558


In [25]:
# %%time
# df_vader["neg_score"], df_vader["neut_score"], df_vader["pos_score"], df_vader["final_score"]= zip(*df_vader['body'].apply(sentiment_score))
# df_vader['vader_sentiment'] = df_vader["final_score"].apply(sentiment)

df_vader.head()

from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import balanced_accuracy_score
for i in np.arange(0,1.05, 0.05):
    def sentiment_binary(x):
        if x >i: # can be adjusted
            return 1
        else:
            return 0

    df_vader['vader_sentiment_binary'] = df_vader["final_score"].apply(sentiment_binary)
    print(i)
    print(precision_score(df_vader['sentiment_binary'], df_vader['vader_sentiment_binary']))
    print(f1_score(df_vader['sentiment_binary'], df_vader['vader_sentiment_binary']))
    print(balanced_accuracy_score(df_vader['sentiment_binary'], df_vader['vader_sentiment_binary']))
    print('break')

0.0
0.484073928430987
0.48917146830915953
0.528449175160127
break
0.05
0.48588469184890654
0.48831168831168825
0.5298096688186558
break
0.1
0.4898373983739837
0.4868686868686869
0.5327314593485646
break
0.15000000000000002
0.4925124792013311
0.48385778504290966
0.5343498703048272
break
0.2
0.4942577626541897
0.48006610204503203
0.5351005890852507
break
0.25
0.5017809439002672
0.4759290540540541
0.5397430334877356
break
0.30000000000000004
0.4949053857350801
0.44825313117996046
0.5312614244908945
break
0.35000000000000003
0.4974120082815735
0.4346449570330167
0.5310845917849457
break
0.4
0.5014459224985541
0.4109978667930789
0.5303818140183274
break
0.45
0.5116938341601701
0.3701614970520379
0.53010829580409
break
0.5
0.512987012987013
0.339602364320258
0.526874286073939
break
0.55
0.5156826568265682
0.3128147733631785
0.524719819591805
break
0.6000000000000001
0.5184357541899441
0.2741506646971935
0.5213154050011316
break
0.65
0.5258741258741259
0.2346333853354134
0.5189831684189241
br

## Add in specific words to improve sentiment

In [18]:
# !cp "/content/drive/MyDrive/Colab Notebooks/new_sentiment.csv" "new_sentiment.csv"
df_vader['sentiment_binary'] = df_vader['sentiment'].apply(lambda x: 1 if x==1 else 0)

new_sentiment = pd.read_csv('new_sentiment.csv')
new_sentiment = dict(zip(new_sentiment['word'], new_sentiment['sentiment']))
## reference the positive negative neutral sentiment list

def sentiment_score_tuned(x):
    SIA = SentimentIntensityAnalyzer()
    SIA.lexicon.update(new_sentiment)
    scores = list(SIA.polarity_scores(x).values())
    return scores[0], scores[1], scores[2], scores[3]


def sentiment_binary(x):
    if x >0.05: # can be adjusted
        return 1
    else:
        return 0
    
    
def metrics_binary(x):
    from sklearn.metrics import confusion_matrix
    from sklearn.metrics import f1_score
    from sklearn.metrics import precision_score
    from sklearn.metrics import recall_score
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import balanced_accuracy_score
    print(confusion_matrix(x['sentiment_binary'], x['vader_sentiment_binary'], labels= [0,1]))
    print('F1 score no weighting')
    print(f1_score(x['sentiment_binary'], x['vader_sentiment_binary'],average=None))
    print('Precision Score')
    print(precision_score(x['sentiment_binary'], x['vader_sentiment_binary']))
    print('Balanced Accuracy')
    print(balanced_accuracy_score(x['sentiment_binary'], x['vader_sentiment_binary']))

In [19]:
%%time
df_vader = df_vader.copy(deep=True)

df_vader["neg_score"], df_vader["neut_score"], df_vader["pos_score"], df_vader["final_score"]= zip(*df_vader['body'].apply(sentiment_score_tuned))
df_vader['vader_sentiment_binary'] = df_vader["final_score"].apply(sentiment_binary)

metrics_binary(df_vader)
df_vader.head()

[[1282 1717]
 [ 492 1998]]
F1 score no weighting
[0.53718835 0.64399678]
Precision Score
0.5378196500672947
Balanced Accuracy
0.6149427319146543
Wall time: 1min 14s


sentiment                                               body  neg_score  \
0          0  Thanks but you’ve lost me at \n\n„If look at A...      0.135   
1          1  Awesome 😎! Why the moon 🤔 Let’s shoot AMC out ...      0.060   
2          1  If you look at AMCs business page you’ll find ...      0.027   
3          1  I bought 20 today, i am also a retarded dumb m...      0.079   
4          0  Ahh, my fellow Retard. I see the more and more...      0.222   

   neut_score  pos_score  final_score  vader_sentiment  \
0       0.776      0.089      -0.2500               -1   
1       0.522      0.418       0.9468                1   
2       0.622      0.351       0.9564                1   
3       0.286      0.635       0.9783               -1   
4       0.710      0.068      -0.6096               -1   

   vader_sentiment_binary  sentiment_binary  
0                       0                 0  
1                       1                 1  
2                       1                 1  
3                       1                 1  
4                       0                 0

In [21]:
#0.6 is the sweet spot that maxmiese all metrics at 0.6
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import balanced_accuracy_score
for i in np.arange(0,1.05, 0.05):
  def sentiment_binary(x):
      if x >i: # can be adjusted
          return 1
      else:
          return 0

  df_vader['vader_sentiment_binary'] = df_vader["final_score"].apply(sentiment_binary)
  print(i)
  print(precision_score(df_vader['sentiment_binary'], df_vader['vader_sentiment_binary']))
  print(f1_score(df_vader['sentiment_binary'], df_vader['vader_sentiment_binary']))
  print(balanced_accuracy_score(df_vader['sentiment_binary'], df_vader['vader_sentiment_binary']))
  print('break')

0.0
0.53588644884842
0.6429948586118253
0.6128775857012578
break
0.05
0.5378196500672947
0.643996776792909
0.6149427319146543
break
0.1
0.5421325334060539
0.6457690433652753
0.619270144934523
break
0.15000000000000002
0.5447513812154696
0.6454991816693945
0.6212256829920548
break
0.2
0.5469319137013169
0.6443307476481268
0.6223780081981811
break
0.25
0.5520504731861199
0.6441358541074117
0.6261260446922736
break
0.30000000000000004
0.555786350148368
0.6392491467576793
0.6265212232725501
break
0.35000000000000003
0.5611161662117076
0.6393640919301883
0.6302388614143135
break
0.4
0.5698517817723115
0.6384031089913443
0.635442269243697
break
0.45
0.5867740852635113
0.6392393490583288
0.6457689377048039
break
0.5
0.5970823202500868
0.6403427081393184
0.6517829236251441
break
0.55
0.6076728193992038
0.6392537597563298
0.6564216854078535
break
0.6000000000000001
0.6232718894009217
0.6372202591283864
0.6623490962851071
break
0.65
0.639654463183875
0.6319853688274741
0.6662003130896377
break
0

# Expand to full data set

In [3]:
nltk.download('vader_lexicon')
!pip install vaderSentiment
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\chuaz\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


In [4]:
# !cp "/content/drive/MyDrive/Colab Notebooks/new_sentiment.csv" "new_sentiment.csv"
new_sentiment = pd.read_csv('new_sentiment.csv')
new_sentiment = dict(zip(new_sentiment['word'], new_sentiment['sentiment']))
## reference the positive negative neutral sentiment list

def sentiment_score_tuned(x):
    try:
        SIA = SentimentIntensityAnalyzer()
        SIA.lexicon.update(new_sentiment)
        scores = list(SIA.polarity_scores(x).values())
        return scores[0], scores[1], scores[2], scores[3]
    except:
        return 'error!'


def sentiment_binary(x):
    try:
        if x >0.6: # can be adjusted
            return 1
        else:
            return 0
    except:
        return 'error!'
      
    

In [6]:
# !cp "/content/drive/MyDrive/Colab Notebooks/combined_comments.csv" "combined_comments.csv"

data = pd.read_csv(r'C:\Users\chuaz\OneDrive\MSBA\Sem 4\BT5153\Project\combined_comments.csv')
data.head()

C:\ProgramData\Anaconda3\envs\5153env\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (3,7) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


filename                author  \
0  SUPRATIK_0.csv             [deleted]   
1  SUPRATIK_0.csv             okgeezeok   
2  SUPRATIK_0.csv  LegitimateInjury5720   
3  SUPRATIK_0.csv             [deleted]   
4  SUPRATIK_0.csv            jawnlerdoe   

                                              body  created_utc       id  \
0                                        [removed]  1.61232e+09  glt6x5e   
1                     https://youtu.be/gmq1ueWGKgY  1.61214e+09  gljgye5   
2                                   And to da moon  1.61197e+09  glbe5gt   
3                                        [removed]  1.61191e+09  gl7to3u   
4  I’m all in at open too. We’re in this together.   1.6119e+09  gl71p20   

     link_id                                          permalink score  \
0  t3_l7c2a3  /r/wallstreetbets/comments/l7c2a3/fuck_the_hed...     1   
1  t3_l7c2a3  /r/wallstreetbets/comments/l7c2a3/fuck_the_hed...     1   
2  t3_l7c2a3  /r/wallstreetbets/comments/l7c2a3/fuck_the_hed...     1   
3  t3_l7c2a3  /r/wallstreetbets/comments/l7c2a3/fuck_the_hed...     1   
4  t3_l7c2a3  /r/wallstreetbets/comments/l7c2a3/fuck_the_hed...     1   

        subreddit search_term  \
0  wallstreetbets      l7c2a3   
1  wallstreetbets      l7c2a3   
2  wallstreetbets      l7c2a3   
3  wallstreetbets      l7c2a3   
4  wallstreetbets      l7c2a3   

                                           post_name  
0  Fuck the hedge funds; diamond hands. AMC to th...  
1  Fuck the hedge funds; diamond hands. AMC to th...  
2  Fuck the hedge funds; diamond hands. AMC to th...  
3  Fuck the hedge funds; diamond hands. AMC to th...  
4  Fuck the hedge funds; diamond hands. AMC to th...

In [7]:
data = data[data['body']!='[removed]']
data.head()

filename                author  \
1  SUPRATIK_0.csv             okgeezeok   
2  SUPRATIK_0.csv  LegitimateInjury5720   
4  SUPRATIK_0.csv            jawnlerdoe   
7  SUPRATIK_0.csv          JokersKnight   
9  SUPRATIK_0.csv            JoeWelburg   

                                              body  created_utc       id  \
1                     https://youtu.be/gmq1ueWGKgY  1.61214e+09  gljgye5   
2                                   And to da moon  1.61197e+09  glbe5gt   
4  I’m all in at open too. We’re in this together.   1.6119e+09  gl71p20   
7     Invest it has such a strong really behind it  1.61189e+09  gl6tpoi   
9      AMC will legit go through the roof tomorrow  1.61189e+09  gl6pihh   

     link_id                                          permalink score  \
1  t3_l7c2a3  /r/wallstreetbets/comments/l7c2a3/fuck_the_hed...     1   
2  t3_l7c2a3  /r/wallstreetbets/comments/l7c2a3/fuck_the_hed...     1   
4  t3_l7c2a3  /r/wallstreetbets/comments/l7c2a3/fuck_the_hed...     1   
7  t3_l7c2a3  /r/wallstreetbets/comments/l7c2a3/fuck_the_hed...     1   
9  t3_l7c2a3  /r/wallstreetbets/comments/l7c2a3/fuck_the_hed...     2   

        subreddit search_term  \
1  wallstreetbets      l7c2a3   
2  wallstreetbets      l7c2a3   
4  wallstreetbets      l7c2a3   
7  wallstreetbets      l7c2a3   
9  wallstreetbets      l7c2a3   

                                           post_name  
1  Fuck the hedge funds; diamond hands. AMC to th...  
2  Fuck the hedge funds; diamond hands. AMC to th...  
4  Fuck the hedge funds; diamond hands. AMC to th...  
7  Fuck the hedge funds; diamond hands. AMC to th...  
9  Fuck the hedge funds; diamond hands. AMC to th...

In [9]:
%%time
data["neg_score"], data["neut_score"], data["pos_score"], data["final_score"]= zip(*data['body'].apply(sentiment_score_tuned))
data['vader_sentiment'] = data["final_score"].apply(sentiment_binary)

Wall time: 3h 41min 40s


In [10]:
data.to_csv('combine_comments_vader.csv')

# import shutil

# shutil.copy('combine_comments_vader.csv', '/content/drive/MyDrive/Colab Notebooks/combine_comments_vader.csv')

# Merge w BERT data frame

In [12]:
bert = pd.read_csv(r'C:\Users\chuaz\OneDrive\MSBA\Sem 4\BT5153\Project\combined_comments_bert_logits.csv')
bert

C:\ProgramData\Anaconda3\envs\5153env\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (4,8) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Unnamed: 0        filename                author  \
0                0  SUPRATIK_0.csv             okgeezeok   
1                1  SUPRATIK_0.csv  LegitimateInjury5720   
2                2  SUPRATIK_0.csv            jawnlerdoe   
3                3  SUPRATIK_0.csv          JokersKnight   
4                4  SUPRATIK_0.csv            JoeWelburg   
...            ...             ...                   ...   
810184      810184  ZONGXIAN_2.csv        MyNi_NotYourNi   
810185      810185  ZONGXIAN_2.csv        Ok_Bottle_2198   
810186      810186  ZONGXIAN_2.csv           inntw-inutw   
810187      810187  ZONGXIAN_2.csv         Forrest_GUHmp   
810188      810188  ZONGXIAN_2.csv             VisualMod   

                                                     body  created_utc  \
0                            https://youtu.be/gmq1ueWGKgY  1.61214e+09   
1                                          And to da moon  1.61197e+09   
2         I’m all in at open too. We’re in this together.   1.6119e+09   
3            Invest it has such a strong really behind it  1.61189e+09   
4             AMC will legit go through the roof tomorrow  1.61189e+09   
...                                                   ...          ...   
810184          ... and all they got was a weird haircut.   1639102296   
810185  Musk fanboys are definitely the dumbest breed ...   1639102292   
810186       Alright, ima head out .. to get my knee pads   1639102206   
810187  Where's the loss porn? Did that guy with stupi...   1639101702   
810188  \n**User Report**| | | |\n:--|:--|:--|:--\n**T...   1639101536   

             id    link_id                                          permalink  \
0       gljgye5  t3_l7c2a3  /r/wallstreetbets/comments/l7c2a3/fuck_the_hed...   
1       glbe5gt  t3_l7c2a3  /r/wallstreetbets/comments/l7c2a3/fuck_the_hed...   
2       gl71p20  t3_l7c2a3  /r/wallstreetbets/comments/l7c2a3/fuck_the_hed...   
3       gl6tpoi  t3_l7c2a3  /r/wallstreetbets/comments/l7c2a3/fuck_the_hed...   
4       gl6pihh  t3_l7c2a3  /r/wallstreetbets/comments/l7c2a3/fuck_the_hed...   
...         ...        ...                                                ...   
810184  hnxm4z1  t3_rcx695  /r/wallstreetbets/comments/rcx695/129_tsla_spl...   
810185  hnxm4nh  t3_rcx695  /r/wallstreetbets/comments/rcx695/129_tsla_spl...   
810186  hnxlxye  t3_rcx695  /r/wallstreetbets/comments/rcx695/129_tsla_spl...   
810187  hnxkt8u  t3_rcx695  /r/wallstreetbets/comments/rcx695/129_tsla_spl...   
810188  hnxkf9p  t3_rcx695  /r/wallstreetbets/comments/rcx695/129_tsla_spl...   

       score       subreddit search_term  \
0          1  wallstreetbets      l7c2a3   
1          1  wallstreetbets      l7c2a3   
2          1  wallstreetbets      l7c2a3   
3          1  wallstreetbets      l7c2a3   
4          2  wallstreetbets      l7c2a3   
...      ...             ...         ...   
810184    27  wallstreetbets      rcx695   
810185    26  wallstreetbets      rcx695   
810186     7  wallstreetbets      rcx695   
810187    14  wallstreetbets      rcx695   
810188     1  wallstreetbets      rcx695   

                                                post_name  \
0       Fuck the hedge funds; diamond hands. AMC to th...   
1       Fuck the hedge funds; diamond hands. AMC to th...   
2       Fuck the hedge funds; diamond hands. AMC to th...   
3       Fuck the hedge funds; diamond hands. AMC to th...   
4       Fuck the hedge funds; diamond hands. AMC to th...   
...                                                   ...   
810184                          12/9 TSLA Split They Said   
810185                          12/9 TSLA Split They Said   
810186                          12/9 TSLA Split They Said   
810187                          12/9 TSLA Split They Said   
810188                          12/9 TSLA Split They Said   

                                                   clean2  \
0                                                     NaN   
1                                        

In [21]:
df = data.reset_index().drop('index',axis=1).join(bert[['Class_0 Logits BERT', 'CLass_1 Logits BERT']] )

In [26]:
data.isna().sum()

filename               0
author                 1
body                3184
created_utc        29466
id                 29490
link_id            32672
permalink          32675
score              29498
subreddit          29498
search_term        29508
post_name          32687
neg_score              0
neut_score             0
pos_score              0
final_score            0
vader_sentiment        0
dtype: int64

In [24]:
df = df[['id', 'link_id','neg_score', 'neut_score', 'pos_score', 'final_score', 'Class_0 Logits BERT', 'CLass_1 Logits BERT']]

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 810189 entries, 0 to 810188
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   id                   780699 non-null  object 
 1   link_id              777517 non-null  object 
 2   neg_score            810189 non-null  object 
 3   neut_score           810189 non-null  object 
 4   pos_score            810189 non-null  object 
 5   final_score          810189 non-null  object 
 6   Class_0 Logits BERT  810189 non-null  float64
 7   CLass_1 Logits BERT  810189 non-null  float64
dtypes: float64(2), object(6)
memory usage: 49.5+ MB


<class 'pandas.core.frame.DataFrame'>
Int64Index: 777517 entries, 0 to 810188
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   id                   777517 non-null  object 
 1   link_id              777517 non-null  object 
 2   neg_score            777517 non-null  object 
 3   neut_score           777517 non-null  object 
 4   pos_score            777517 non-null  object 
 5   final_score          777517 non-null  object 
 6   Class_0 Logits BERT  777517 non-null  float64
 7   CLass_1 Logits BERT  777517 non-null  float64
dtypes: float64(2), object(6)
memory usage: 53.4+ MB


In [29]:
df.dropna().to_csv('combined_comments_vader_bert_outputs.csv')